apiVersion: v1
kind: Service
metadata:
  name: calendar-service
  namespace: default
  labels:
    app: calendar-app
spec:
  selector:
    app: calendar-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381492094663:role/EKSPodAccess
  name: calendar-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appt-handler-deployment
  namespace: default
  labels:
    app: calendar-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-app
  template:
    metadata:
      labels:
        app: calendar-app
    spec:
      containers:
      - name: appt-handler
        image: 381492094663.dkr.ecr.us-east-1.amazonaws.com/calendar-app:appt-handler
        ports:
        - containerPort: 80
      serviceAccountName: calendar-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-handler-deployment
  namespace: default
  labels:
    app: calendar-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-app
  template:
    metadata:
      labels:
        app: calendar-app
    spec:
      containers:
      - name: calendar-handler
        image: 381492094663.dkr.ecr.us-east-1.amazonaws.com/calendar-app:calendar-handler
        ports:
        - containerPort: 80
      serviceAccountName: calendar-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: default
  labels:
    app: calendar-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-app
  template:
    metadata:
      labels:
        app: calendar-app
    spec:
      containers:
      - name: client
        image: 381492094663.dkr.ecr.us-east-1.amazonaws.com/calendar-app:client
        ports:
        - containerPort: 80
      serviceAccountName: calendar-sa
